version: '3.8'

services:
  datamed-postgres:
    image: postgres:13.4-alpine
    container_name: datamed-postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./datamed-postgres-volume:/var/lib/postgresql/data
    networks:
      - docker_skilldevs

  datamed-api:
    stdin_open: true
    tty: true
    container_name: datamed-api
    image: rzlams/datamed-api
    restart: always
    working_dir: /app
    env_file:
      - ./.env
    environment:
      - VIRTUAL_HOST=datamed-api.skilldevs.shop,www.datamed-api.skilldevs.shop
      - VIRTUAL_PORT=4000
    depends_on:
      - datamed-postgres
    networks:
      - docker_skilldevs

  datamed-web:
    stdin_open: true
    tty: true
    container_name: datamed-web
    restart: always
    image: rzlams/datamed-web
    environment:
      - VIRTUAL_HOST=datamed.skilldevs.shop,www.datamed.skilldevs.shop
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=datamed.skilldevs.shop,www.datamed.skilldevs.shop
      - LETSENCRYPT_EMAIL=skilldevs.shop@gmail.com
    networks:
      - docker_skilldevs

networks:
  docker_skilldevs:
    external: true
