version: '3.8'

services:
  adminer:
    image: adminer
    restart: always
    env_file:
      - ../.env
    environment:
      - VIRTUAL_HOST=adminer.skilldevs.shop
      - VIRTUAL_PORT=8080
    networks:
      - docker_skilldevs

networks:
  docker_skilldevs:
    external: true
