version: '3.8'

services:
  skill-devs:
    stdin_open: true
    tty: true
    container_name: skill-devs
    image: skill-devs
    build:
      context: ..
      dockerfile: Dockerfile
      target: development
    restart: always
    working_dir: /app
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src:ro
    ports:
      - 4000:4000
    networks:
      - skill-devs
