version: '3.8'

services:
  skilldevs:
    stdin_open: true
    tty: true
    container_name: skilldevs
    image: rzlams/agency-api
    restart: always
    working_dir: /app
    env_file:
      - ../.env
    environment:
      - VIRTUAL_HOST=skilldevs.shop
      - VIRTUAL_PORT=4000
    depends_on:
      - postgres
    networks:
      - skilldevs

  nginx:
    stdin_open: true
    tty: true
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    env_file:
      - ../.env
    depends_on:
      - skilldevs
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - skilldevs
