version: '3.8'

services:
  postgres:
    image: postgres:13.4-alpine
    container_name: postgres
    restart: always
    env_file:
      - ../.env
    volumes:
      - ./agency-postgres-volume:/var/lib/postgresql/data
    networks:
      - skilldevs

networks:
  skilldevs:
    driver: bridge
